@startuml
title WarmHouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of Warmhouse inc.")
Person(admin, "Admin", "An administrator managing the system")
System(WarmHouseSystem, "WarmHouse System", "System managing sensors, warmdevices")

System_Ext(device, "Device", "External API for device controller. Heater, sensor etc.")

Rel(user, WarmHouseSystem, "Uses the system")
Rel(admin,WarmHouseSystem,"Manages the system")
Rel(admin,device,"Register device in the system")
Rel(WarmHouseSystem,device,"Calls device controller")

@enduml